# Development Configuration for Likha Licensing Platform
# This configuration is automatically loaded when SPRING_PROFILES_ACTIVE=dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/likha_licensing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    open-in-view: false
    defer-datasource-initialization: false  # Let Flyway handle initialization

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    # Ensure Flyway runs early in the Spring Boot lifecycle
    out-of-order: false
    placeholder-replacement: true

  # Spring Modulith Configuration
  modulith:
    events:
      externalization:
        enabled: false  # Disable event externalization to avoid circular dependency
      republish-outstanding-events-on-restart: false
      # Ensure proper event store initialization
      jdbc-schema-initialization:
        enabled: false  # Let Flyway handle schema creation

  # Development Tools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # Security Configuration (Development)
  security:
    user:
      name: admin
      password: admin123

  # Redis Configuration (Optional)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
    include-message: always

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,flyway,liquibase,modulith
  endpoint:
    health:
      show-details: always

# Application Specific Configuration
app:
  multitenancy:
    enabled: true
    default-tenant: default
    tenant-header: X-Tenant-ID
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
  jwt:
    secret: dev-secret-key-change-in-production
    expiration: 86400000 # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    app.likha: DEBUG
    org.springframework.modulith: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"