# CI Configuration for Likha Licensing Platform
# This configuration is used for GitHub Actions CI environment

spring:
  application:
    name: likha-licensing-platform-ci

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:likha_licensing}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    defer-datasource-initialization: false

  # Enable Flyway for CI to create schema
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

  # Spring Modulith
  modulith:
    events:
      externalization:
        enabled: false
      jdbc-schema-initialization:
        enabled: false

# Server Configuration for CI
server:
  port: 0  # Random port for tests

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Application Configuration for CI
app:
  multitenancy:
    enabled: true
    default-tenant: ci-tenant
    tenant-header: X-Tenant-ID
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"

# Logging Configuration for CI
logging:
  level:
    root: WARN
    app.likha: INFO
    org.springframework.modulith: WARN
    org.springframework.boot: WARN
    org.flywaydb: INFO